params:
  _target_: "src.models.cbm.ConceptBottleneckModel"
  input_dim: ${dataset.metadata.input_dim}
  n_concepts: ${dataset.metadata.n_concepts}
  n_labels: ${dataset.metadata.n_labels}
  task_penalty: ${task_penalty}
  task_interpretable: true
  train_backbone: ${dataset.metadata.finetune_backbone}
  p_int_train: 0.25

metadata:
  name: cbm_linear