params:
  _target_: "src.models.cem.ConceptEmbeddingModel"
  in_features: ${dataset.metadata.input_dim}
  n_concepts: ${dataset.metadata.n_concepts}
  emb_size: ${c_emb_size}
  n_classes: ${dataset.metadata.n_labels}
  task_penalty: ${task_penalty}
  p_int_train: ${p_int_train}
  train_backbone: ${dataset.metadata.finetune_backbone}

metadata:
  name: cem
