params:
  _target_: "src.models.vcem.VariationalConceptEmbeddingModel"
  in_size: ${dataset.metadata.input_dim}
  n_concepts: ${dataset.metadata.n_concepts}
  n_classes: ${dataset.metadata.n_labels}
  emb_size: ${c_emb_size}
  task_penalty: ${task_penalty}
  kl_penalty: ${kl_penalty}
  train_backbone: ${dataset.metadata.finetune_backbone}
  p_int_train: null # not used in V-CEM
  sampling: true

metadata:
  name: v_cem