params:
  _target_: "src.models.v_cem.VariationalConceptEmbeddingModel"
  in_size: ${dataset.metadata.input_dim}
  n_concepts: ${dataset.metadata.n_concepts}
  n_classes: ${dataset.metadata.n_labels}
  emb_size: ${c_emb_size}
  task_penalty: ${task_penalty}
  kl_penalty: ${kl_penalty}
  p_int_train: ${p_int_train}
  train_backbone: ${dataset.metadata.finetune_backbone}
  sampling: false

metadata:
  name: v_cem_no_sampling