defaults:
  - dataset: mnist_addition
  - model: blackbox

## Working directory
root: /home/bigdata-01QYD/s280037/Adversary-Aware-Concept-Embedding-Model/

## Traninging parameters
max_epochs: 10 #500
patience: 20
batch_size: 128
lr: 0.0001
gamma: 0.5
lr_step: 100

## Model parameters
task_penalty: 0.1

# Only for concept embedding models
c_emb_size: 16
p_int_train: 0.25 

# Shared experimental parameters
val_size: 0.1
seed: 1
gpus: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      dataset: mnist_addition
      model: v_cem #blackbox, cbm_mlp, cem, v_cem
      seed: 1 # 


wandb:
  project: "v_cem"        # Set your project name here
  entity: "francescothesantis-politecnico-di-torino"  # Set your entity name here

note: test
