defaults:
  - dataset: mnist_addition
  - model: blackbox

## Working directory
root: /home/fdesantis/Adversary-Aware-Concept-Embedding-Model

## Traninging parameters
max_epochs: 200 # 200
patience: 20
batch_size: 256
gamma: 0.5
lr_step: 100

## Model parameters
task_penalty: 0.1

# Only for concept embedding models
c_emb_size: 16

# Shared experimental parameters
val_size: 0.1
seed: 1
gpus: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1 #1, 2, 3, 4, 5
      dataset: mnist_addition, imdb, celeba, cub, cebab # mnist_addition_incomplete
      model: blackbox, cbm_mlp, cem, v_cem # cbm_linear

wandb:
  project: "v_cem"        # Set your project name here
  entity: "francescothesantis-politecnico-di-torino"  # Set your entity name here

note: test
