defaults:
  - dataset: mnist_addition
  - model: blackbox

## Working directory
root: /home/fdesantis/Adversary-Aware-Concept-Embedding-Model

## Traninging parameters
max_epochs: 500
patience: 20
batch_size: 128
gamma: 0.5
lr_step: 100

## Model parameters
task_penalty: 0.1

# Only for concept embedding models
c_emb_size: 16
p_int_train: 0.25

# Only for V-CEM
# This parameter is specified here instead of in the model-specific configuration file
# in order to facilitate the sweep and the logs of such parameter
kl_penalty: 0.05

# backbone parameters
img_backbone_emb_size: 512
text_backbone_emb_size: 768

# Shared experimental parameters
val_size: 0.1
seed: 1
gpus: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1, 2, 3 #, 4, 5
      dataset: cebab, imdb, mnist_even_odd, mnist_addition, celeba
      model: prob_cbm, v_cem, cbm_mlp, cem, cbm_linear, blackbox 

wandb:
  project: "v_cem"        # Set your project name here
  entity: "francescothesantis-politecnico-di-torino"  # Set your entity name here

note: test