
defaults:
  - dataset: mnist_addition
  - model: blackbox

# substitute with your root directory
root: /home/bigdata-01QYD/s280037/Adversary-Aware-Concept-Embedding-Model/
devices: 1
optimizer: adam
max_epochs: 500
patience: 40
batch_size: 128
input_dim: 784 # output dimension of vit32
seed: 1
c_emb_size: 16
p_int_training: 0.25

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1 # 
      dataset: mnist_addition
      model: blackbox #, cbm_linear, cbm_mlp #, cem, v_cem





wandb:
  project: "v_cem"        # Set your project name here
  entity: "francescothesantis-politecnico-di-torino"  # Set your entity name here


note: test
