defaults:
  - dataset: mnist_addition
  - model: blackbox

## Working directory
root: /home/fdesantis/Adversary-Aware-Concept-Embedding-Model

## Traninging parameters
max_epochs: 100 # 200
patience: 20
batch_size: 512
gamma: 0.5
lr_step: 50

## Model parameters
task_penalty: 0.1

# Only for concept embedding models
c_emb_size: 32

# Only for V-CEM
# This parameter is specified here instead of in the model-specific configuration file
# in order to facilitate the sweep and the logs of such parameter
kl_penalty: null

# Shared experimental parameters
val_size: 0.1
seed: 1
gpus: 1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      seed: 1 #1, 2, 3, 4, 5
      dataset: celeba # celeba, cub, cebab, imdb, mnist_addition, mnist_addition_incomplete
      model: v_cem #v_cem, cem, cbm_mlp, cbm_linear, blackbox 
      kl_penalty: 0.01, 0.1, 1.0

wandb:
  project: "v_cem"        # Set your project name here
  entity: "francescothesantis-politecnico-di-torino"  # Set your entity name here

note: test
