loader:
  _target_: src.loaders.text_loaders.text_loader
  dataset: cebab
  root: ${root}
  batch_size: ${batch_size}  
  
metadata:
  n_concepts: 4
  n_labels: 3
  input_dim: ${text_backbone_emb_size}
  lr: 0.0005
  name: cebab
  finetune_backbone: false
