loader:
  _target_: src.loaders.image_loaders.CelebA_loader
  batch_size: ${batch_size}  
  seed: ${seed}
  val_size: ${val_size}
  num_workers: 3
  root: ${root}
  concept_names: ["Mouth_Slightly_Open", "Smiling", "Wearing_Lipstick", "High_Cheekbones", "Heavy_Makeup", "Wavy_Hair", "Oval_Face", "Pointy_Nose", "Arched_Eyebrows", "Big_Lips"]
  class_attributes: ["Male"]

metadata:
  n_concepts: 10
  n_labels: 2
  input_dim: 1000 # output dimension of the vit32 cls
  lr: 0.0001
  name: celeba


