loader:
  _target_: src.loaders.image_loaders.CelebA_loader
  batch_size: ${batch_size}  
  seed: ${seed}
  val_size: ${val_size}
  num_workers: 3
  root: ${root}
  concept_names: ["No_Beard", "Young", "Attractive", "Mouth_Slightly_Open", "Smiling", "Wearing_Lipstick", "High_Cheekbones"]
  class_attributes: ["Wavy_Hair", "Black_Hair", "Male"]
  finetune_backbone: false

#ID:           Attribute:  Balance:
#24             No_Beard  0.834940
#39                Young  0.773617
#2            Attractive  0.512505
#21  Mouth_Slightly_Open  0.483428
#31              Smiling  0.482080
#36     Wearing_Lipstick  0.472436
#19      High_Cheekbones  0.455032
#20                 Male  0.416754

metadata:
  n_concepts: 7
  n_labels: 8
  input_dim: ${img_backbone_emb_size}
  lr: 0.0001
  name: celeba
  finetune_backbone: ${dataset.loader.finetune_backbone}


