loader:
  _target_: src.loaders.image_loaders.CUB200_loader
  batch_size: ${batch_size}  
  seed: ${seed}
  val_size: ${val_size}
  num_workers: 3
  root: ${root}

metadata:
  n_concepts: 112
  n_labels: 200
  input_dim: ${img_backbone_emb_size}
  lr: 0.0001
  name: cub
  finetune_backbone: true
