loader:
  _target_: src.loaders.image_loaders.MNIST_addition_loader
  batch_size: ${batch_size}  
  seed: ${seed}
  val_size: ${val_size}
  num_workers: 3
  root: ${root}
  incomplete: false

metadata:
  n_concepts: 10
  n_labels: 20
  input_dim: ${img_backbone_emb_size}
  lr: 0.002
  name: mnist_addition
  finetune_backbone: false
