loader:
  _target_: src.loaders.image_loaders.MNIST_addition_loader
  batch_size: ${batch_size}  
  seed: ${seed}
  val_size: ${val_size}
  num_workers: 3
  root: ${root}

metadata:
  n_concepts: 10
  n_labels: 20
  name: mnist_addition
