loader:
  _target_: src.loaders.toy_loaders.toy_loader_function
  dataset: "or"
  batch_size: ${batch_size}  
  train_size: 1000
  val_size: 100
  test_size: 100

metadata:
  n_concepts: 2
  n_labels: 2
  input_dim: 2
  lr: 0.005
  name: or
  finetune_backbone: false
